app:
    port: 9900
    database:
        name: "svc-role"

database:
    mongodb:
        uri: mongodb://localhost:27017/
        name: svc-role
        options:
            useNewUrlParser: true
            useUnifiedTopology: true
            auth:
                user: "root"
                password: "changeit"

    eventstore:
        poolMax:
        poolMin:
        streamProtocol: "http"
        hostname: "localhost"
        httpPort: 2113
        httpPotocol: "http"
        tcpPassword: "changeit"
        tcpUsername: "admin"
        tcpPort: 1113
        tcpProtocol: tcp

    redis:
        host: "localhost"
        port: "6379"
        password: ""
