account:
    port: 9900
    cache:
        name: "notification-queue"

sendgrid:
    apiKey: "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"
    sender: "Aleus_noreply <no-reply@aleus.app>"

database:
    mongodb:
        uri: mongodb://localhost:27017/
        name: svc-notification
        options:
            useNewUrlParser: true
            useUnifiedTopology: true
            auth:
                user: "root"
                password: "changeit"

    eventstore:
        poolMax:
        poolMin:
        streamProtocol: "http"
        hostname: "localhost"
        httpPort: 2113
        httpPotocol: "http"
        tcpPassword: "changeit"
        tcpUsername: "admin"
        tcpPort: 1113
        tcpProtocol: tcp

    redis:
        host: "localhost"
        port: "6379"
        password: ""
