billing:
    port: 9900
    database:
        name: "svc-billing"

stripe:
    apiKey: "*******_6776"

database:
    mongodb:
        uri: mongodb://localhost:27017/
        name: svc-billing
        options:
            auth:
                user: "root"
                pass: "changeit"

    eventstore:
        poolMax:
        poolMin:
        streamProtocol: "http"
        hostname: "localhost"
        httpPort: 2113
        httpPotocol: "http"
        tcpPassword: "changeit"
        tcpUsername: "admin"
        tcpPort: 1113
        tcpProtocol: tcp

    redis:
        host: "localhost"
        port: "6379"
        password: ""
