billing:
    port: 9900
    database:
        name: "svc-billing"

stripe:
    apiKey: sk_test_51IBv6sD5hZ1P68xfO8Ks17mPHbaDXT5AHTUoOhxhxfpNezSTjCo3mSLRGNsLcV7Htg9IE5c9jRZF0sBTtFHVc8Yu00xNBSEpin

database:
    mongodb:
        uri: mongodb://localhost:27017/
        name: svc-billing
        options:
            useNewUrlParser: true
            auth:
                user: "root"
                password: "changeit"

    eventstore:
        poolMax:
        poolMin:
        streamProtocol: "http"
        hostname: "localhost"
        httpPort: 2113
        httpPotocol: "http"
        tcpPassword: "changeit"
        tcpUsername: "admin"
        tcpPort: 1113
        tcpProtocol: tcp

    redis:
        host: "localhost"
        port: "6379"
        password: ""
